Support loading ecryptfs passphrase from abpw.

diff --git a/easy-ecryptfs b/easy-ecryptfs
--- a/easy-ecryptfs
+++ b/easy-ecryptfs
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Version 1.0
+# Version 1.1
 set -euo pipefail
 
 BASENAME="$(basename "$0")"
@@ -53,7 +53,7 @@ getpass() {
             ;;
     esac
 
-    read -s -p "$prompt" ans
+    read -r -s -p "$prompt" ans
 
     echo -n "$ans"
 
@@ -65,6 +65,21 @@ random_hex_key() {
     bytes="$1"
     log_debug "Generating ${bytes}-byte key"
     head -c "$bytes" /dev/random | xxd -p | tr -d '\n'
+}
+
+# usage: read_abpw_path_from_config FILENAME
+#
+# Given an easy-ecryptfs config file, parse out the abpw_path
+# The file should be simple "key=value" lines, with no whitespace. Any special
+# characters in value are treated as is.
+read_abpw_path_from_config() {
+    if [ ! -f "$1" ]; then
+        echo >&2 "error: Expected to find easy-ecryptfs.conf at '$1'"
+        echo >&2 "PWD: $PWD"
+        return 1
+    fi
+    log_debug "Reading config from '$(readlink -m "$1")'"
+    grep '^abpw_path=' "$1" | cut -d '=' -f '2-'
 }
 
 # usage: read_label_from_config FILENAME
@@ -106,19 +121,22 @@ run() {
     "$@"
 }
 
-# usage: load_passphrase DIRECTORY
+# usage: load_passphrase DIRECTORY PASSWORD
 #
 # Using the wrapped ecryptfs passphrase found at DIRECTORY/wrapped-passphrase,
-# prompt for the wrapping password, unwrap the wrapped passphrase and insert it
-# into the kernel keyring with ecryptfs-insert-wrapped-passphrase-into-keyring.
+# prompt for the wrapping password if not given as PASSWORD, unwrap the wrapped
+# passphrase and insert it into the kernel keyring with
+# ecryptfs-insert-wrapped-passphrase-into-keyring.
 #
 load_passphrase() {
-    local dir filename
+    local dir filename passwd
     dir="$1"
     if [ ! -d "$dir" ]; then
         echo >&2 "error: no such directory: $dir"
         return 1
     fi
+
+    passwd="$2"
 
     filename="$(readlink -f "$dir/wrapped-passphrase")"
     if ! [ -e "$filename" ]; then
@@ -131,7 +149,13 @@ load_passphrase() {
         # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870335
         run keyctl link @u @s
     fi
-    run ecryptfs-insert-wrapped-passphrase-into-keyring "$filename"
+
+    if [ -z "$passwd" ]; then
+        run ecryptfs-insert-wrapped-passphrase-into-keyring "$filename"
+    else
+        run ecryptfs-insert-wrapped-passphrase-into-keyring "$filename" \
+            <<< "$passwd"
+    fi
 }
 
 # usage: resolve_label LABEL
@@ -197,7 +221,8 @@ EOM
 }
 
 cmd_mount() {
-    local name label lower_dir mount_dir config_file
+    local name label lower_dir mount_dir config_file easy_config_file
+    local abpw_path password
     name="$1"
 
     label="$(resolve_label "$name")"
@@ -205,7 +230,17 @@ cmd_mount() {
     config_file="$ECRYPTFS_CONFIG_DIR/$label.conf"
     lower_dir="$(head -1 "$config_file" | cut -f1 -d' ')/.."
 
-    load_passphrase "$lower_dir"
+    easy_config_file="$lower_dir/easy-ecryptfs.conf"
+    abpw_path=
+    if [ -e "$easy_config_file" ]; then
+        abpw_path="$(read_abpw_path_from_config "$easy_config_file" || true)"
+    fi
+    password=
+    if [ -n "$abpw_path" ]; then
+        password="$(run abpw get "$abpw_path" pass)"
+    fi
+
+    load_passphrase "$lower_dir" "$password"
 
     run mount.ecryptfs_private "$label"
 }
@@ -296,8 +331,8 @@ EOM
     fi
 
     # Validate each signature is hex of the expected length
-    echo "$sigs" | while read line; do
-        if egrep -vq "^[0-9a-fA-F]{$KEYBYTES,$KEYBYTES}$" <<< "$line"; then
+    echo "$sigs" | while read -r line; do
+        if grep -vEq "^[0-9a-fA-F]{$KEYBYTES,$KEYBYTES}$" <<< "$line"; then
             echo >&2 "Invalid hex key signature: '$line'"
             return 3
         fi
