Handle other default git branch names.
In git-rm-merged-branches and git-checkout-main, try looking at
origin/HEAD if there's neither a master nor a main branch.

diff --git a/git-checkout-main b/git-checkout-main
--- a/git-checkout-main
+++ b/git-checkout-main
@@ -8,29 +8,41 @@ run() {
     "$@"
 }
 
+# Determine the main/master branch and echo its name.
 git-main-branch() {
     local ret
-    git rev-parse --verify --quiet master >/dev/null && ret=$? || ret=$?
+    git rev-parse --verify --quiet main >/dev/null && ret=$? || ret=$?
 
     case "$ret" in
         0)
-            echo master
+            echo main
             return
             ;;
         1)
             # pass
             ;;
         *)
+            # probably not a git repo / some other error
             return "$ret"
             ;;
     esac
 
-    if git rev-parse --verify --quiet main >/dev/null; then
-        echo main
-    else
-        echo >&2 "Neither master nor main exists"
-        return 1
+    if git rev-parse --verify --quiet master >/dev/null; then
+        echo master
+        return
     fi
+
+    local head_ref
+    if head_ref=$(git rev-parse --verify --quiet --abbrev-ref origin/HEAD)
+    then
+        echo "$head_ref" | cut -d/ -f2
+        return
+    fi
+
+    echo >&2 "Error: could not determine the default branch name"
+    echo >&2 "* Neither master nor main exists"
+    echo >&2 "* Also could not determine default branch from origin/HEAD"
+    return 1
 }
 
 # check out the master/main branch
diff --git a/git-rm-merged-branches b/git-rm-merged-branches
--- a/git-rm-merged-branches
+++ b/git-rm-merged-branches
@@ -18,6 +18,7 @@ each branch by squashing the branch and cherry picking the result to see if
 there is any remaining diff.)
 
 The default branch is assumed to be called 'main' or 'master'.
+If neither of these exist, try to parse origin/HEAD.
 
 Exclusions:
 - The currently checked out branch is ignored
@@ -92,10 +93,20 @@ git-main-branch() {
 
     if git rev-parse --verify --quiet master >/dev/null; then
         echo master
-    else
-        echo >&2 "Neither master nor main exists"
-        return 1
+        return
     fi
+
+    local head_ref
+    if head_ref=$(git rev-parse --verify --quiet --abbrev-ref origin/HEAD)
+    then
+        echo "$head_ref" | cut -d/ -f2
+        return
+    fi
+
+    echo >&2 "Error: could not determine the default branch name"
+    echo >&2 "* Neither master nor main exists"
+    echo >&2 "* Also could not determine default branch from origin/HEAD"
+    return 1
 }
 
 
